finansai2/Controllers/IslaidosController.cs
using finansai2.Models;
using finansai2.ViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace finansai2.Controllers
{
    public class IslaidosController : Controller
    {
        private ApplicationDbContext _context;

        public IslaidosController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new IslaidaFormViewModel()
            {
                Kategorijos = _context.Kategorijos.ToList()
            };
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
     //   [ValidateAntiForgeryToken]
        public ActionResult Create(IslaidaFormViewModel viewModel)
        {

            if (!ModelState.IsValid)
            {
                viewModel.Kategorijos = _context.Kategorijos.ToList();
                return View("Create", viewModel);
            }

            var islaida = new Islaida
            {
                IsleidejasId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                KategorijaId = viewModel.Kategorija,
                Suma = viewModel.Suma
            };
            _context.Islaidos.Add(islaida);

            _context.SaveChanges();

            return RedirectToAction("Index", "Home");

        }
    }
}

finansai2/Controllers/KategorijosController.cs
using finansai2.Models;
using finansai2.ViewModels;
using System.Web.Mvc;

namespace finansai2.Controllers
{
    public class KategorijosController : Controller
    {

        private readonly ApplicationDbContext _context;

        public KategorijosController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize]
        public ActionResult AddKategorija()
        {
            return View();
        }


        [Authorize]
        [HttpPost]
      //  [ValidateAntiForgeryToken]
        public ActionResult AddKategorija(KategorijaFormViewModel viewModel)
        {

            if (!ModelState.IsValid)
            {
                return View("AddKategorija", viewModel);
            }

            //  var name = _context.Kategorijos.Single(k => k.Name == viewModel.Name);
           // var id = _context.Kategorijos.Max(p => p.Id);
            var kategorija = new Kategorija
            { 
                Name = viewModel.Name
            };

            _context.Kategorijos.Add(kategorija);

            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

    }
}

finansai2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Finansu sekimo sistema.</title>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Expense tracking", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add an expense", "Create", "Islaidos")</li>
                    <li>@Html.ActionLink("Add a category", "AddKategorija", "Kategorijos")</li>
                    <li>@Html.ActionLink("View expenses", "Perziureti", "Perziureti")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Emilis Masionis</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>